"""new features phase 1-3: print history, lab results, alerts priority, stock reservations, treatment protocol, injections, patient documents

Revision ID: 06e7e7d26b2e
Revises: e4a6fc4335ac
Create Date: 2026-09-03 00:16:44.087322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '06e7e7d26b2e'
down_revision: Union[str, None] = 'e4a6fc4335ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_reservations',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('procedure_entity_type', sa.String(length=64), nullable=False),
    sa.Column('procedure_entity_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('HELD', 'CONSUMED', 'RELEASED', name='reservationstatus'), nullable=False),
    sa.Column('reserved_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['reserved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_reservations_item_id'), 'stock_reservations', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_reservations_procedure_entity_id'), 'stock_reservations', ['procedure_entity_id'], unique=False)
    op.create_index(op.f('ix_stock_reservations_status'), 'stock_reservations', ['status'], unique=False)
    op.create_table('print_logs',
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('context_entity_type', sa.String(length=64), nullable=True),
    sa.Column('context_entity_id', sa.String(length=64), nullable=True),
    sa.Column('printed_by_id', sa.UUID(), nullable=False),
    sa.Column('printed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['printed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_print_logs_document_type'), 'print_logs', ['document_type'], unique=False)
    op.create_index(op.f('ix_print_logs_patient_id'), 'print_logs', ['patient_id'], unique=False)
    op.create_index(op.f('ix_print_logs_printed_at'), 'print_logs', ['printed_at'], unique=False)
    op.create_table('visa_support_requests',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='visasupportstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('handled_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['handled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visa_support_requests_patient_id'), 'visa_support_requests', ['patient_id'], unique=False)
    op.create_index(op.f('ix_visa_support_requests_status'), 'visa_support_requests', ['status'], unique=False)
    op.create_table('injection_administrations',
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('medicine_name', sa.String(length=255), nullable=False),
    sa.Column('dose', sa.String(length=64), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'ADMINISTERED', 'SKIPPED', name='injectionstatus'), nullable=False),
    sa.Column('administered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('administered_by_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['administered_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['ivf_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_injection_administrations_cycle_id'), 'injection_administrations', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_injection_administrations_scheduled_at'), 'injection_administrations', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_injection_administrations_status'), 'injection_administrations', ['status'], unique=False)
    op.create_table('treatment_protocols',
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['ivf_cycles.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_protocols_cycle_id'), 'treatment_protocols', ['cycle_id'], unique=False)
    op.create_table('lab_results',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('parameter_name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('reference_range', sa.String(length=64), nullable=True),
    sa.Column('flag', sa.Enum('NORMAL', 'LOW', 'HIGH', 'CRITICAL', name='labresultflag'), nullable=False),
    sa.Column('entered_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entered_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['lab_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_results_order_id'), 'lab_results', ['order_id'], unique=False)
    # server_default set explicitly (autogenerate leaves this out) so this
    # ADD COLUMN ... NOT NULL is safe against a notification_tasks table
    # that already has rows in it — the empty dev database happens to have
    # zero rows today, but this migration must not assume that; per spec
    # §28/§32's migration-safety requirement.
    # Unlike create_table, add_column does NOT auto-create the enum TYPE it
    # references — it has to already exist in Postgres. autogenerate leaves
    # this out; created explicitly here (checkfirst=True so this migration
    # stays re-runnable, per spec §28's idempotency requirement).
    bind = op.get_bind()
    sa.Enum('FOLLOW_UP', 'PROCEDURE_REMINDER', 'EGG_EVENT', 'MEDICATION_REMINDER', 'FRONT_DESK', 'OTHER', name='alerttype').create(bind, checkfirst=True)
    sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='taskpriority').create(bind, checkfirst=True)
    sa.Enum('NOT_REQUIRED', 'PENDING', 'VERIFIED', 'REJECTED', name='documentverificationstatus').create(bind, checkfirst=True)

    op.add_column('inventory_items', sa.Column('reserved_qty', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('notification_tasks', sa.Column('patient_id', sa.UUID(), nullable=True))
    op.add_column('notification_tasks', sa.Column('alert_type', sa.Enum('FOLLOW_UP', 'PROCEDURE_REMINDER', 'EGG_EVENT', 'MEDICATION_REMINDER', 'FRONT_DESK', 'OTHER', name='alerttype'), nullable=False, server_default='OTHER'))
    op.add_column('notification_tasks', sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='taskpriority'), nullable=False, server_default='NORMAL'))
    op.add_column('notification_tasks', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_notification_tasks_alert_type'), 'notification_tasks', ['alert_type'], unique=False)
    op.create_index(op.f('ix_notification_tasks_patient_id'), 'notification_tasks', ['patient_id'], unique=False)
    op.create_index(op.f('ix_notification_tasks_priority'), 'notification_tasks', ['priority'], unique=False)
    op.create_foreign_key(None, 'notification_tasks', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'notification_tasks', 'patients', ['patient_id'], ['id'])
    op.add_column('patient_documents', sa.Column('verification_status', sa.Enum('NOT_REQUIRED', 'PENDING', 'VERIFIED', 'REJECTED', name='documentverificationstatus'), nullable=False, server_default='NOT_REQUIRED'))
    op.add_column('patient_documents', sa.Column('verified_by_id', sa.UUID(), nullable=True))
    op.add_column('patient_documents', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_patient_documents_verification_status'), 'patient_documents', ['verification_status'], unique=False)
    op.create_foreign_key(None, 'patient_documents', 'users', ['verified_by_id'], ['id'])
    op.add_column('patients', sa.Column('nationality', sa.String(length=64), nullable=True))
    op.add_column('patients', sa.Column('is_international', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('patients', sa.Column('photo_document_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_patients_is_international'), 'patients', ['is_international'], unique=False)
    op.create_foreign_key('fk_patients_photo_document_id', 'patients', 'patient_documents', ['photo_document_id'], ['id'], use_alter=True)
    # NOTE: autogenerate also proposed `create_unique_constraint('uq_role_permission', ...)`
    # here — deliberately dropped. That name already belongs to
    # role_permissions' composite PRIMARY KEY (pre-existing, unrelated to
    # this change); autogenerate mistook it for a missing plain UNIQUE
    # constraint because the model declares one with the same name. The PK
    # already enforces the exact uniqueness the model's UniqueConstraint
    # wants, so adding it for real would just collide on the constraint
    # name. Not this migration's problem to fix.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_patients_photo_document_id', 'patients', type_='foreignkey')
    op.drop_index(op.f('ix_patients_is_international'), table_name='patients')
    op.drop_column('patients', 'photo_document_id')
    op.drop_column('patients', 'is_international')
    op.drop_column('patients', 'nationality')
    op.drop_constraint(None, 'patient_documents', type_='foreignkey')
    op.drop_index(op.f('ix_patient_documents_verification_status'), table_name='patient_documents')
    op.drop_column('patient_documents', 'verified_at')
    op.drop_column('patient_documents', 'verified_by_id')
    op.drop_column('patient_documents', 'verification_status')
    op.drop_constraint(None, 'notification_tasks', type_='foreignkey')
    op.drop_constraint(None, 'notification_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_notification_tasks_priority'), table_name='notification_tasks')
    op.drop_index(op.f('ix_notification_tasks_patient_id'), table_name='notification_tasks')
    op.drop_index(op.f('ix_notification_tasks_alert_type'), table_name='notification_tasks')
    op.drop_column('notification_tasks', 'created_by_id')
    op.drop_column('notification_tasks', 'priority')
    op.drop_column('notification_tasks', 'alert_type')
    op.drop_column('notification_tasks', 'patient_id')
    op.drop_column('inventory_items', 'reserved_qty')
    bind = op.get_bind()
    sa.Enum(name='documentverificationstatus').drop(bind, checkfirst=True)
    sa.Enum(name='taskpriority').drop(bind, checkfirst=True)
    sa.Enum(name='alerttype').drop(bind, checkfirst=True)
    op.drop_index(op.f('ix_lab_results_order_id'), table_name='lab_results')
    op.drop_table('lab_results')
    op.drop_index(op.f('ix_treatment_protocols_cycle_id'), table_name='treatment_protocols')
    op.drop_table('treatment_protocols')
    op.drop_index(op.f('ix_injection_administrations_status'), table_name='injection_administrations')
    op.drop_index(op.f('ix_injection_administrations_scheduled_at'), table_name='injection_administrations')
    op.drop_index(op.f('ix_injection_administrations_cycle_id'), table_name='injection_administrations')
    op.drop_table('injection_administrations')
    op.drop_index(op.f('ix_visa_support_requests_status'), table_name='visa_support_requests')
    op.drop_index(op.f('ix_visa_support_requests_patient_id'), table_name='visa_support_requests')
    op.drop_table('visa_support_requests')
    op.drop_index(op.f('ix_print_logs_printed_at'), table_name='print_logs')
    op.drop_index(op.f('ix_print_logs_patient_id'), table_name='print_logs')
    op.drop_index(op.f('ix_print_logs_document_type'), table_name='print_logs')
    op.drop_table('print_logs')
    op.drop_index(op.f('ix_stock_reservations_status'), table_name='stock_reservations')
    op.drop_index(op.f('ix_stock_reservations_procedure_entity_id'), table_name='stock_reservations')
    op.drop_index(op.f('ix_stock_reservations_item_id'), table_name='stock_reservations')
    op.drop_table('stock_reservations')
    # ### end Alembic commands ###
