"""lab report ingestion and async report jobs

Revision ID: 094de4bcd5b1
Revises: a147ba0be789
Create Date: 2026-09-03 21:47:50.766835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '094de4bcd5b1'
down_revision: Union[str, None] = 'a147ba0be789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_jobs',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('report_type', sa.Enum('patient_summary', name='report_job_type'), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='report_job_status'), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('storage_key', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_report_jobs_created_at_id', 'report_jobs', [sa.text('created_at DESC'), sa.text('id DESC')], unique=False)
    op.create_index('ix_report_jobs_status', 'report_jobs', ['status'], unique=False)
    op.create_table('lab_reports',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('document_sha256', sa.String(length=64), nullable=False),
    sa.Column('document_kind', sa.Enum('digital_pdf', 'scanned_pdf', 'image', 'unknown', name='lab_document_kind'), nullable=False),
    sa.Column('extraction_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='lab_extraction_status'), nullable=False),
    sa.Column('extraction_method', sa.Enum('native_pdf_text', 'ocr', 'ai_vision', 'manual', 'none', name='lab_extraction_method'), nullable=False),
    sa.Column('extraction_error', sa.String(length=500), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_lab_reports_created_at_id', 'lab_reports', [sa.text('created_at DESC'), sa.text('id DESC')], unique=False)
    op.create_index('ix_lab_reports_patient_created_at', 'lab_reports', ['patient_id', sa.text('created_at DESC')], unique=False)
    op.create_table('lab_report_results',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('test_name', sa.String(length=200), nullable=True),
    sa.Column('value', sa.String(length=120), nullable=True),
    sa.Column('unit', sa.String(length=60), nullable=True),
    sa.Column('reference_range', sa.String(length=120), nullable=True),
    sa.Column('extracted_test_name', sa.String(length=200), nullable=True),
    sa.Column('extracted_value', sa.String(length=120), nullable=True),
    sa.Column('extracted_unit', sa.String(length=60), nullable=True),
    sa.Column('extracted_reference_range', sa.String(length=120), nullable=True),
    sa.Column('entry_origin', sa.Enum('extracted', 'manual', name='lab_entry_origin'), nullable=False),
    sa.Column('normalization_match', sa.Enum('exact_alias', 'unmatched', 'manual', name='lab_normalization_match'), nullable=False),
    sa.Column('normalization_note', sa.String(length=300), nullable=True),
    sa.Column('validation_status', sa.Enum('ok', 'needs_review', 'not_extracted', name='lab_result_validation_status'), nullable=False),
    sa.Column('validation_notes', sa.JSON(), nullable=False),
    sa.Column('source_snippet', sa.String(length=500), nullable=True),
    sa.Column('source_location', sa.String(length=120), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['lab_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lab_report_results_report_id_id', 'lab_report_results', ['report_id', 'id'], unique=False)
    op.create_table('lab_report_result_corrections',
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.Enum('test_name', 'value', 'unit', 'reference_range', name='lab_correction_field'), nullable=False),
    sa.Column('previous_value', sa.String(length=200), nullable=True),
    sa.Column('new_value', sa.String(length=200), nullable=True),
    sa.Column('corrected_by_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['corrected_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['lab_report_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lab_report_result_corrections_result_id_created_at', 'lab_report_result_corrections', ['result_id', 'created_at'], unique=False)
    # NOTE: autogenerate also proposed `op.create_unique_constraint(
    # 'uq_role_permission', 'role_permissions', ...)`. That is a pre-existing
    # drift between app.roles.models and the initial schema on `main`, unrelated
    # to this change, so it is intentionally NOT applied here.
    # ### end Alembic commands ###


# Enum types this revision creates. Dropped explicitly on downgrade — Postgres
# keeps a named type after its table is gone, which would break a re-upgrade.
_ENUMS = (
    "report_job_type",
    "report_job_status",
    "lab_document_kind",
    "lab_extraction_status",
    "lab_extraction_method",
    "lab_entry_origin",
    "lab_normalization_match",
    "lab_result_validation_status",
    "lab_correction_field",
)


def downgrade() -> None:
    op.drop_index('ix_lab_report_result_corrections_result_id_created_at', table_name='lab_report_result_corrections')
    op.drop_table('lab_report_result_corrections')
    op.drop_index('ix_lab_report_results_report_id_id', table_name='lab_report_results')
    op.drop_table('lab_report_results')
    op.drop_index('ix_lab_reports_patient_created_at', table_name='lab_reports')
    op.drop_index('ix_lab_reports_created_at_id', table_name='lab_reports')
    op.drop_table('lab_reports')
    op.drop_index('ix_report_jobs_status', table_name='report_jobs')
    op.drop_index('ix_report_jobs_created_at_id', table_name='report_jobs')
    op.drop_table('report_jobs')
    bind = op.get_bind()
    for name in _ENUMS:
        sa.Enum(name=name).drop(bind, checkfirst=True)
