"""donor management module

Revision ID: 19a781018fea
Revises: 06e7e7d26b2e
Create Date: 2026-09-03 00:25:43.557677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '19a781018fea'
down_revision: Union[str, None] = '06e7e7d26b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donors',
    sa.Column('donor_code', sa.String(length=32), nullable=False),
    sa.Column('category', sa.Enum('SELF_DONOR', 'SELF_EMBRYO', 'DONOR', 'BANK_STORAGE', 'DONOR_EMBRYO', name='donorcategory'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'RETIRED', name='donorstatus'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('screening_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donors_category'), 'donors', ['category'], unique=False)
    op.create_index(op.f('ix_donors_donor_code'), 'donors', ['donor_code'], unique=True)
    op.create_index(op.f('ix_donors_status'), 'donors', ['status'], unique=False)
    op.create_table('donor_benchmarks',
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=128), nullable=False),
    sa.Column('expected_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('threshold_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_underperforming', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donor_benchmarks_donor_id'), 'donor_benchmarks', ['donor_id'], unique=False)
    op.create_index(op.f('ix_donor_benchmarks_is_underperforming'), 'donor_benchmarks', ['is_underperforming'], unique=False)
    op.create_table('donor_matches',
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('couple_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('matched_by_id', sa.UUID(), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.ForeignKeyConstraint(['matched_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donor_matches_donor_id'), 'donor_matches', ['donor_id'], unique=False)
    op.create_index(op.f('ix_donor_matches_is_active'), 'donor_matches', ['is_active'], unique=False)
    op.create_index(op.f('ix_donor_matches_patient_id'), 'donor_matches', ['patient_id'], unique=False)
    op.create_index('uq_donor_one_active_match', 'donor_matches', ['donor_id'], unique=True, postgresql_where=sa.text('is_active'))
    # NOTE: autogenerate also proposed create_unique_constraint('uq_role_permission', ...)
    # here — deliberately dropped, same pre-existing false-positive
    # explained in 06e7e7d26b2e (that name already belongs to
    # role_permissions' composite PRIMARY KEY, unrelated to this change).
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_donor_one_active_match', table_name='donor_matches', postgresql_where=sa.text('is_active'))
    op.drop_index(op.f('ix_donor_matches_patient_id'), table_name='donor_matches')
    op.drop_index(op.f('ix_donor_matches_is_active'), table_name='donor_matches')
    op.drop_index(op.f('ix_donor_matches_donor_id'), table_name='donor_matches')
    op.drop_table('donor_matches')
    op.drop_index(op.f('ix_donor_benchmarks_is_underperforming'), table_name='donor_benchmarks')
    op.drop_index(op.f('ix_donor_benchmarks_donor_id'), table_name='donor_benchmarks')
    op.drop_table('donor_benchmarks')
    op.drop_index(op.f('ix_donors_status'), table_name='donors')
    op.drop_index(op.f('ix_donors_donor_code'), table_name='donors')
    op.drop_index(op.f('ix_donors_category'), table_name='donors')
    op.drop_table('donors')
    # ### end Alembic commands ###
