"""whatsapp sms messaging module

Revision ID: a147ba0be789
Revises: bda9b371fa4b
Create Date: 2026-09-03 00:38:03.609420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a147ba0be789'
down_revision: Union[str, None] = 'bda9b371fa4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_templates',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('channel', sa.Enum('WHATSAPP', 'SMS', name='messagechannel'), nullable=False),
    sa.Column('category', sa.Enum('TRANSACTIONAL', 'PROMOTIONAL', name='messagecategory'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('message_logs',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.Enum('WHATSAPP', 'SMS', name='messagechannel'), nullable=False),
    sa.Column('category', sa.Enum('TRANSACTIONAL', 'PROMOTIONAL', name='messagecategory'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'DELIVERED', 'FAILED', name='messagestatus'), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('sent_by_id', sa.UUID(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['sent_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_logs_category'), 'message_logs', ['category'], unique=False)
    op.create_index(op.f('ix_message_logs_patient_id'), 'message_logs', ['patient_id'], unique=False)
    op.create_index(op.f('ix_message_logs_status'), 'message_logs', ['status'], unique=False)
    op.create_table('patient_comms_preferences',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('promotional_opt_in', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_comms_preferences_patient_id'), 'patient_comms_preferences', ['patient_id'], unique=True)
    # NOTE: autogenerate also proposed create_unique_constraint('uq_role_permission', ...)
    # here — deliberately dropped, same pre-existing false-positive
    # explained in 06e7e7d26b2e.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_comms_preferences_patient_id'), table_name='patient_comms_preferences')
    op.drop_table('patient_comms_preferences')
    op.drop_index(op.f('ix_message_logs_status'), table_name='message_logs')
    op.drop_index(op.f('ix_message_logs_patient_id'), table_name='message_logs')
    op.drop_index(op.f('ix_message_logs_category'), table_name='message_logs')
    op.drop_table('message_logs')
    op.drop_table('message_templates')
    # ### end Alembic commands ###
