"""prescriptions, consent forms, mrd records

Revision ID: bda9b371fa4b
Revises: 19a781018fea
Create Date: 2026-09-03 00:32:20.027415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bda9b371fa4b'
down_revision: Union[str, None] = '19a781018fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mrd_records',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('record_type', sa.String(length=128), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mrd_records_patient_id'), 'mrd_records', ['patient_id'], unique=False)
    op.create_table('consent_forms',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('couple_id', sa.UUID(), nullable=True),
    sa.Column('form_type', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SIGNED', 'WITHDRAWN', name='consentformstatus'), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_forms_patient_id'), 'consent_forms', ['patient_id'], unique=False)
    op.create_index(op.f('ix_consent_forms_status'), 'consent_forms', ['status'], unique=False)
    op.create_table('prescriptions',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=True),
    sa.Column('prescribed_by_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['ivf_cycles.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['prescribed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_cycle_id'), 'prescriptions', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_patient_id'), 'prescriptions', ['patient_id'], unique=False)
    op.create_table('prescription_lines',
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('medicine_id', sa.UUID(), nullable=True),
    sa.Column('medicine_name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=64), nullable=False),
    sa.Column('frequency', sa.String(length=64), nullable=False),
    sa.Column('timing', sa.String(length=64), nullable=True),
    sa.Column('duration', sa.String(length=64), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_lines_prescription_id'), 'prescription_lines', ['prescription_id'], unique=False)
    # NOTE: autogenerate also proposed create_unique_constraint('uq_role_permission', ...)
    # here — deliberately dropped, same pre-existing false-positive
    # explained in 06e7e7d26b2e.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescription_lines_prescription_id'), table_name='prescription_lines')
    op.drop_table('prescription_lines')
    op.drop_index(op.f('ix_prescriptions_patient_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_cycle_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_consent_forms_status'), table_name='consent_forms')
    op.drop_index(op.f('ix_consent_forms_patient_id'), table_name='consent_forms')
    op.drop_table('consent_forms')
    op.drop_index(op.f('ix_mrd_records_patient_id'), table_name='mrd_records')
    op.drop_table('mrd_records')
    # ### end Alembic commands ###
