"""initial schema

Revision ID: c9f299fef0e3
Revises: 
Create Date: 2026-08-27 06:37:20.832741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c9f299fef0e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('source_ip', postgresql.INET(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('inventory_items',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('IVF_CONSUMABLES', 'CRYOGENIC_SUPPLIES', 'LAB_SUPPLIES', 'SURGICAL_EQUIPMENT', name='inventorycategory'), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('last_restocked', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_category'), 'inventory_items', ['category'], unique=False)
    op.create_index(op.f('ix_inventory_items_name'), 'inventory_items', ['name'], unique=False)
    op.create_table('lab_test_catalogue',
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('turnaround_time', sa.String(length=64), nullable=False),
    sa.Column('sample_type', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_name')
    )
    op.create_table('ledger_accounts',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('debit_paise', sa.Integer(), nullable=False),
    sa.Column('credit_paise', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('medicines',
    sa.Column('generic_name', sa.String(length=255), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('strength', sa.String(length=64), nullable=True),
    sa.Column('dosage_form', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('hsn_code', sa.String(length=16), nullable=True),
    sa.Column('gst_percent', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('minimum_stock', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicines_generic_name'), 'medicines', ['generic_name'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatch_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_created_at'), 'outbox_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_dispatched_at'), 'outbox_events', ['dispatched_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_table('packages',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('validity_description', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_module'), 'permissions', ['module'], unique=False)
    op.create_table('procedure_charges',
    sa.Column('service_code', sa.String(length=64), nullable=False),
    sa.Column('procedure_name', sa.String(length=255), nullable=False),
    sa.Column('charge_paise', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_code')
    )
    op.create_table('qa_task_templates',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUAL', name='qafrequency'), nullable=False),
    sa.Column('checklist_description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('medicine_batches',
    sa.Column('medicine_id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.String(length=64), nullable=False),
    sa.Column('manufacturing_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('purchase_rate_paise', sa.Integer(), nullable=False),
    sa.Column('selling_rate_paise', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicine_batches_expiry_date'), 'medicine_batches', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_medicine_batches_medicine_id'), 'medicine_batches', ['medicine_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_table('users',
    sa.Column('employee_code', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_employee_code'), 'users', ['employee_code'], unique=True)
    op.create_table('assets',
    sa.Column('asset_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('brand', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('serial_number', sa.String(length=128), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('cost_paise', sa.Integer(), nullable=True),
    sa.Column('current_location', sa.String(length=255), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('warranty_until', sa.Date(), nullable=True),
    sa.Column('amc_until', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'UNDER_MAINTENANCE', 'SENT_FOR_SERVICE', 'RETIRED', name='assetstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_code'), 'assets', ['asset_code'], unique=True)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_table('employees',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=False),
    sa.Column('designation', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('joined_date', sa.Date(), nullable=False),
    sa.Column('reporting_manager_id', sa.UUID(), nullable=True),
    sa.Column('leave_balance_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reporting_manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notification_tasks',
    sa.Column('assigned_to_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'DONE', 'ESCALATED', name='taskstatus'), nullable=False),
    sa.Column('resolution', sa.String(length=128), nullable=True),
    sa.Column('escalated_to_id', sa.UUID(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=64), nullable=True),
    sa.Column('related_entity_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['escalated_to_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_tasks_assigned_to_id'), 'notification_tasks', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_notification_tasks_due_at'), 'notification_tasks', ['due_at'], unique=False)
    op.create_index(op.f('ix_notification_tasks_status'), 'notification_tasks', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('tone', sa.Enum('INFO', 'SUCCESS', 'ATTENTION', 'CRITICAL', name='notificationtone'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('link_entity_type', sa.String(length=64), nullable=True),
    sa.Column('link_entity_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('patients',
    sa.Column('uhid', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.Column('blood_group', sa.String(length=8), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('occupation', sa.String(length=128), nullable=True),
    sa.Column('emergency_contact', sa.String(length=255), nullable=True),
    sa.Column('referral_source', sa.String(length=255), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('primary_doctor_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['primary_doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_full_name'), 'patients', ['full_name'], unique=False)
    op.create_index(op.f('ix_patients_phone'), 'patients', ['phone'], unique=False)
    op.create_index(op.f('ix_patients_uhid'), 'patients', ['uhid'], unique=True)
    op.create_table('purchase_orders',
    sa.Column('po_number', sa.String(length=32), nullable=False),
    sa.Column('item_description', sa.String(length=255), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=True),
    sa.Column('medicine_id', sa.UUID(), nullable=True),
    sa.Column('supplier', sa.String(length=255), nullable=False),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'APPROVED', 'DISPATCHED', 'RECEIVED', 'REJECTED', name='purchaseorderstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_index(op.f('ix_purchase_orders_status'), 'purchase_orders', ['status'], unique=False)
    op.create_table('readiness_checklists',
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.Column('checklist_date', sa.Date(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('verified_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readiness_checklists_checklist_date'), 'readiness_checklists', ['checklist_date'], unique=False)
    op.create_index(op.f('ix_readiness_checklists_department'), 'readiness_checklists', ['department'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_label', sa.String(length=255), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.Enum('RESTOCK', 'CONSUMED', 'ADJUSTMENT', 'WRITE_OFF', name='stockmovementtype'), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('performed_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_item_id'), 'stock_movements', ['item_id'], unique=False)
    op.create_table('appointments',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('visit_type', sa.String(length=128), nullable=False),
    sa.Column('channel', sa.Enum('WALK_IN', 'ONLINE', 'PHONE', name='appointmentchannel'), nullable=False),
    sa.Column('status', sa.Enum('REGISTERED', 'ARRIVED', 'WAITING', 'CONSULTATION', 'INVESTIGATION', 'BILLING', 'PHARMACY', 'FOLLOW_UP', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='appointmentstatus'), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_scheduled_at'), 'appointments', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_table('asset_movements',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('from_location', sa.String(length=255), nullable=True),
    sa.Column('to_location', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('performed_by_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_movements_asset_id'), 'asset_movements', ['asset_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_records_attendance_date'), 'attendance_records', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendance_records_employee_id'), 'attendance_records', ['employee_id'], unique=False)
    op.create_table('couples',
    sa.Column('female_patient_id', sa.UUID(), nullable=False),
    sa.Column('male_patient_id', sa.UUID(), nullable=False),
    sa.Column('relationship_info', sa.String(length=255), nullable=True),
    sa.Column('infertility_type', sa.String(length=64), nullable=True),
    sa.Column('infertility_duration', sa.String(length=64), nullable=True),
    sa.Column('previous_iui_cycles', sa.Integer(), nullable=False),
    sa.Column('previous_ivf_cycles', sa.Integer(), nullable=False),
    sa.Column('previous_treatment_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['female_patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['male_patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('female_patient_id'),
    sa.UniqueConstraint('male_patient_id')
    )
    op.create_table('goods_receipt_notes',
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('received_quantity', sa.Integer(), nullable=False),
    sa.Column('damaged_quantity', sa.Integer(), nullable=False),
    sa.Column('free_quantity', sa.Integer(), nullable=False),
    sa.Column('supplier_invoice_number', sa.String(length=64), nullable=True),
    sa.Column('received_by_id', sa.UUID(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_order_id')
    )
    op.create_table('leave_requests',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.String(length=64), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='leavestatus'), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_requests_employee_id'), 'leave_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_status'), 'leave_requests', ['status'], unique=False)
    op.create_table('maintenance_tasks',
    sa.Column('equipment_name', sa.String(length=255), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('task_type', sa.Enum('PREVENTIVE', 'CORRECTIVE', 'AMC_RENEWAL', 'CALIBRATION', name='maintenancetype'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'DUE', 'COMPLETED', 'OVERDUE', name='maintenancestatus'), nullable=False),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('completed_by_id', sa.UUID(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_tasks_due_date'), 'maintenance_tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_status'), 'maintenance_tasks', ['status'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_session_id'), 'refresh_tokens', ['session_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('clinical_timeline_events',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('couple_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.Enum('CONSULTATION', 'INVESTIGATION', 'STIMULATION_START', 'MONITORING_VISIT', 'TRIGGER', 'RETRIEVAL', 'EMBRYOLOGY_UPDATE', 'EMBRYO_TRANSFER', 'PREGNANCY_MILESTONE', 'BILLING', 'DOCUMENT', name='timelineeventtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_entity_type', sa.String(length=64), nullable=False),
    sa.Column('source_entity_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_timeline_events_couple_id'), 'clinical_timeline_events', ['couple_id'], unique=False)
    op.create_index(op.f('ix_clinical_timeline_events_occurred_at'), 'clinical_timeline_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_clinical_timeline_events_patient_id'), 'clinical_timeline_events', ['patient_id'], unique=False)
    op.create_table('consultations',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('consultation_type', sa.String(length=128), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('corrects_consultation_id', sa.UUID(), nullable=True),
    sa.Column('correction_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['corrects_consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_patient_id'), 'consultations', ['patient_id'], unique=False)
    op.create_table('invoices',
    sa.Column('invoice_number', sa.String(length=32), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('couple_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PARTIALLY_PAID', 'PAID', 'OVERRIDDEN', 'CANCELLED', name='invoicestatus'), nullable=False),
    sa.Column('total_amount_paise', sa.Integer(), nullable=False),
    sa.Column('paid_amount_paise', sa.Integer(), nullable=False),
    sa.Column('discount_paise', sa.Integer(), nullable=False),
    sa.Column('discount_reason', sa.String(length=500), nullable=True),
    sa.Column('discount_approved_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ),
    sa.ForeignKeyConstraint(['discount_approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_patient_id'), 'invoices', ['patient_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('ivf_cycles',
    sa.Column('cycle_number', sa.String(length=32), nullable=False),
    sa.Column('couple_id', sa.UUID(), nullable=False),
    sa.Column('primary_doctor_id', sa.UUID(), nullable=False),
    sa.Column('protocol', sa.String(length=128), nullable=False),
    sa.Column('treatment', sa.String(length=128), nullable=False),
    sa.Column('stage', sa.Enum('ASSESSMENT', 'STIMULATION', 'TRIGGER', 'RETRIEVAL', 'EMBRYOLOGY', 'TRANSFER', 'PREGNANCY_FOLLOWUP', 'COMPLETED', name='cyclestage'), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ),
    sa.ForeignKeyConstraint(['primary_doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ivf_cycles_couple_id'), 'ivf_cycles', ['couple_id'], unique=False)
    op.create_index(op.f('ix_ivf_cycles_cycle_number'), 'ivf_cycles', ['cycle_number'], unique=True)
    op.create_index(op.f('ix_ivf_cycles_stage'), 'ivf_cycles', ['stage'], unique=False)
    op.create_table('patient_documents',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('couple_id', sa.UUID(), nullable=True),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_object_key', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False),
    sa.Column('signed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_object_key')
    )
    op.create_index(op.f('ix_patient_documents_couple_id'), 'patient_documents', ['couple_id'], unique=False)
    op.create_index(op.f('ix_patient_documents_patient_id'), 'patient_documents', ['patient_id'], unique=False)
    op.create_table('patient_packages',
    sa.Column('couple_id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('included_service_codes', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_packages_couple_id'), 'patient_packages', ['couple_id'], unique=False)
    op.create_table('billing_overrides',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('authorized_by_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['authorized_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_overrides_invoice_id'), 'billing_overrides', ['invoice_id'], unique=False)
    op.create_table('charges',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('service_code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('covered_by_package', sa.Boolean(), nullable=False),
    sa.Column('source_module', sa.String(length=64), nullable=True),
    sa.Column('source_entity_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charges_invoice_id'), 'charges', ['invoice_id'], unique=False)
    op.create_table('embryos',
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=16), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=8), nullable=False),
    sa.Column('expansion', sa.String(length=64), nullable=True),
    sa.Column('icm_grade', sa.String(length=64), nullable=True),
    sa.Column('trophectoderm_grade', sa.String(length=64), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('UNDER_REVIEW', 'SELECTED_FOR_TRANSFER', 'CRYOPRESERVED', 'NOT_SUITABLE', 'TRANSFERRED', 'DISCARDED', name='embryostatus'), nullable=False),
    sa.Column('embryologist_notes', sa.Text(), nullable=True),
    sa.Column('graded_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['ivf_cycles.id'], ),
    sa.ForeignKeyConstraint(['graded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embryos_cycle_id'), 'embryos', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_embryos_status'), 'embryos', ['status'], unique=False)
    op.create_table('lab_orders',
    sa.Column('order_number', sa.String(length=32), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('test_catalogue_id', sa.UUID(), nullable=True),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('ordered_by_id', sa.UUID(), nullable=False),
    sa.Column('sample_type', sa.String(length=64), nullable=True),
    sa.Column('source', sa.Enum('INTERNAL', 'EXTERNAL', name='labordersource'), nullable=False),
    sa.Column('external_lab_name', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.Enum('ROUTINE', 'URGENT', name='laborderpriority'), nullable=False),
    sa.Column('status', sa.Enum('ORDERED', 'SAMPLE_COLLECTED', 'IN_PROGRESS', 'REPORT_READY', 'DELIVERED', name='laborderstatus'), nullable=False),
    sa.Column('result_document_id', sa.UUID(), nullable=True),
    sa.Column('result_verified_by_id', sa.UUID(), nullable=True),
    sa.Column('result_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ordered_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['result_document_id'], ['patient_documents.id'], ),
    sa.ForeignKeyConstraint(['result_verified_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['test_catalogue_id'], ['lab_test_catalogue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_orders_order_number'), 'lab_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_lab_orders_patient_id'), 'lab_orders', ['patient_id'], unique=False)
    op.create_index(op.f('ix_lab_orders_status'), 'lab_orders', ['status'], unique=False)
    op.create_table('monitoring_visits',
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('cycle_day', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('right_follicles_mm', sa.JSON(), nullable=False),
    sa.Column('left_follicles_mm', sa.JSON(), nullable=False),
    sa.Column('endometrium_mm', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('estradiol_pg_ml', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('lh_miu_ml', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('progesterone_ng_ml', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('doctor_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['ivf_cycles.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_visits_cycle_id'), 'monitoring_visits', ['cycle_id'], unique=False)
    op.create_table('oocyte_assessments',
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('retrieval_date', sa.Date(), nullable=False),
    sa.Column('oocytes_retrieved', sa.Integer(), nullable=False),
    sa.Column('mature_oocytes', sa.Integer(), nullable=False),
    sa.Column('normally_fertilised', sa.Integer(), nullable=False),
    sa.Column('fertilisation_method', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['ivf_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oocyte_assessments_cycle_id'), 'oocyte_assessments', ['cycle_id'], unique=True)
    op.create_table('payments',
    sa.Column('receipt_number', sa.String(length=32), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'UPI', 'CARD', 'BANK_TRANSFER', 'CREDIT', name='paymentmethod'), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('received_by_id', sa.UUID(), nullable=False),
    sa.Column('is_refund', sa.Boolean(), nullable=False),
    sa.Column('refund_reason', sa.String(length=500), nullable=True),
    sa.Column('refund_approved_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['refund_approved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_receipt_number'), 'payments', ['receipt_number'], unique=True)
    op.create_table('pharmacy_sales',
    sa.Column('bill_number', sa.String(length=32), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('prescribed_by_id', sa.UUID(), nullable=True),
    sa.Column('dispensed_by_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('total_amount_paise', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DISPENSED', 'RETURNED', 'PARTIALLY_RETURNED', name='salestatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dispensed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['prescribed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_sales_bill_number'), 'pharmacy_sales', ['bill_number'], unique=True)
    op.create_index(op.f('ix_pharmacy_sales_patient_id'), 'pharmacy_sales', ['patient_id'], unique=False)
    op.create_table('pregnancy_records',
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=True),
    sa.Column('outcome', sa.Enum('PENDING', 'POSITIVE', 'NEGATIVE', 'BIOCHEMICAL_ONLY', name='pregnancyoutcome'), nullable=False),
    sa.Column('estimated_due_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['ivf_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pregnancy_records_cycle_id'), 'pregnancy_records', ['cycle_id'], unique=True)
    op.create_table('procedures',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=True),
    sa.Column('procedure_type', sa.String(length=128), nullable=False),
    sa.Column('ot_room', sa.String(length=64), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('nurse_id', sa.UUID(), nullable=True),
    sa.Column('embryologist_id', sa.UUID(), nullable=True),
    sa.Column('consent_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'PREPARATION', 'READY', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='procedurestatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['ivf_cycles.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['embryologist_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['nurse_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedures_patient_id'), 'procedures', ['patient_id'], unique=False)
    op.create_index(op.f('ix_procedures_scheduled_at'), 'procedures', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_procedures_status'), 'procedures', ['status'], unique=False)
    op.create_table('qa_task_instances',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_by_id', sa.UUID(), nullable=True),
    sa.Column('verified_by_id', sa.UUID(), nullable=True),
    sa.Column('evidence_document_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['patient_documents.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['qa_task_templates.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_task_instances_due_date'), 'qa_task_instances', ['due_date'], unique=False)
    op.create_index(op.f('ix_qa_task_instances_template_id'), 'qa_task_instances', ['template_id'], unique=False)
    op.create_table('treatment_plans',
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('medication_plan', sa.JSON(), nullable=True),
    sa.Column('consent_status', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['ivf_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_plans_cycle_id'), 'treatment_plans', ['cycle_id'], unique=False)
    op.create_table('beta_hcg_results',
    sa.Column('pregnancy_id', sa.UUID(), nullable=False),
    sa.Column('day_label', sa.String(length=32), nullable=False),
    sa.Column('value_miu_ml', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('recorded_at', sa.Date(), nullable=False),
    sa.Column('interpretation', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancy_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cash_book_entries',
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('particulars', sa.String(length=500), nullable=False),
    sa.Column('entry_type', sa.Enum('RECEIPT', 'PAYMENT', name='entrytype'), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('linked_payment_id', sa.UUID(), nullable=True),
    sa.Column('recorded_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['linked_payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_book_entries_entry_date'), 'cash_book_entries', ['entry_date'], unique=False)
    op.create_table('cryo_locations',
    sa.Column('tank', sa.String(length=32), nullable=False),
    sa.Column('canister', sa.String(length=32), nullable=False),
    sa.Column('cane', sa.String(length=32), nullable=False),
    sa.Column('goblet', sa.String(length=32), nullable=False),
    sa.Column('straw', sa.String(length=32), nullable=False),
    sa.Column('embryo_id', sa.UUID(), nullable=True),
    sa.Column('frozen_at', sa.Date(), nullable=True),
    sa.Column('consent_verified', sa.Boolean(), nullable=False),
    sa.Column('renewal_due', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['embryo_id'], ['embryos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('embryo_id'),
    sa.UniqueConstraint('tank', 'canister', 'cane', 'goblet', 'straw', name='uq_cryo_address')
    )
    op.create_table('embryo_transfers',
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('embryo_id', sa.UUID(), nullable=False),
    sa.Column('procedure_doctor_id', sa.UUID(), nullable=False),
    sa.Column('embryologist_id', sa.UUID(), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['ivf_cycles.id'], ),
    sa.ForeignKeyConstraint(['embryo_id'], ['embryos.id'], ),
    sa.ForeignKeyConstraint(['embryologist_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['procedure_doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embryo_transfers_cycle_id'), 'embryo_transfers', ['cycle_id'], unique=False)
    op.create_table('pharmacy_sale_lines',
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('medicine_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_paise', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['medicine_batches.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['pharmacy_sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pregnancy_milestones',
    sa.Column('pregnancy_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('milestone_date', sa.Date(), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancy_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cryo_custody_events',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('embryo_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('performed_by_id', sa.UUID(), nullable=False),
    sa.Column('witnessed_by_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['embryo_id'], ['embryos.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['cryo_locations.id'], ),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['witnessed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cryo_custody_events_embryo_id'), 'cryo_custody_events', ['embryo_id'], unique=False)
    op.create_index(op.f('ix_cryo_custody_events_location_id'), 'cryo_custody_events', ['location_id'], unique=False)
    op.create_table('transfer_checklist_items',
    sa.Column('transfer_id', sa.UUID(), nullable=False),
    sa.Column('item_code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('checked_by_id', sa.UUID(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['checked_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['embryo_transfers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_checklist_items')
    op.drop_index(op.f('ix_cryo_custody_events_location_id'), table_name='cryo_custody_events')
    op.drop_index(op.f('ix_cryo_custody_events_embryo_id'), table_name='cryo_custody_events')
    op.drop_table('cryo_custody_events')
    op.drop_table('pregnancy_milestones')
    op.drop_table('pharmacy_sale_lines')
    op.drop_index(op.f('ix_embryo_transfers_cycle_id'), table_name='embryo_transfers')
    op.drop_table('embryo_transfers')
    op.drop_table('cryo_locations')
    op.drop_index(op.f('ix_cash_book_entries_entry_date'), table_name='cash_book_entries')
    op.drop_table('cash_book_entries')
    op.drop_table('beta_hcg_results')
    op.drop_index(op.f('ix_treatment_plans_cycle_id'), table_name='treatment_plans')
    op.drop_table('treatment_plans')
    op.drop_index(op.f('ix_qa_task_instances_template_id'), table_name='qa_task_instances')
    op.drop_index(op.f('ix_qa_task_instances_due_date'), table_name='qa_task_instances')
    op.drop_table('qa_task_instances')
    op.drop_index(op.f('ix_procedures_status'), table_name='procedures')
    op.drop_index(op.f('ix_procedures_scheduled_at'), table_name='procedures')
    op.drop_index(op.f('ix_procedures_patient_id'), table_name='procedures')
    op.drop_table('procedures')
    op.drop_index(op.f('ix_pregnancy_records_cycle_id'), table_name='pregnancy_records')
    op.drop_table('pregnancy_records')
    op.drop_index(op.f('ix_pharmacy_sales_patient_id'), table_name='pharmacy_sales')
    op.drop_index(op.f('ix_pharmacy_sales_bill_number'), table_name='pharmacy_sales')
    op.drop_table('pharmacy_sales')
    op.drop_index(op.f('ix_payments_receipt_number'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_oocyte_assessments_cycle_id'), table_name='oocyte_assessments')
    op.drop_table('oocyte_assessments')
    op.drop_index(op.f('ix_monitoring_visits_cycle_id'), table_name='monitoring_visits')
    op.drop_table('monitoring_visits')
    op.drop_index(op.f('ix_lab_orders_status'), table_name='lab_orders')
    op.drop_index(op.f('ix_lab_orders_patient_id'), table_name='lab_orders')
    op.drop_index(op.f('ix_lab_orders_order_number'), table_name='lab_orders')
    op.drop_table('lab_orders')
    op.drop_index(op.f('ix_embryos_status'), table_name='embryos')
    op.drop_index(op.f('ix_embryos_cycle_id'), table_name='embryos')
    op.drop_table('embryos')
    op.drop_index(op.f('ix_charges_invoice_id'), table_name='charges')
    op.drop_table('charges')
    op.drop_index(op.f('ix_billing_overrides_invoice_id'), table_name='billing_overrides')
    op.drop_table('billing_overrides')
    op.drop_index(op.f('ix_patient_packages_couple_id'), table_name='patient_packages')
    op.drop_table('patient_packages')
    op.drop_index(op.f('ix_patient_documents_patient_id'), table_name='patient_documents')
    op.drop_index(op.f('ix_patient_documents_couple_id'), table_name='patient_documents')
    op.drop_table('patient_documents')
    op.drop_index(op.f('ix_ivf_cycles_stage'), table_name='ivf_cycles')
    op.drop_index(op.f('ix_ivf_cycles_cycle_number'), table_name='ivf_cycles')
    op.drop_index(op.f('ix_ivf_cycles_couple_id'), table_name='ivf_cycles')
    op.drop_table('ivf_cycles')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_patient_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_consultations_patient_id'), table_name='consultations')
    op.drop_table('consultations')
    op.drop_index(op.f('ix_clinical_timeline_events_patient_id'), table_name='clinical_timeline_events')
    op.drop_index(op.f('ix_clinical_timeline_events_occurred_at'), table_name='clinical_timeline_events')
    op.drop_index(op.f('ix_clinical_timeline_events_couple_id'), table_name='clinical_timeline_events')
    op.drop_table('clinical_timeline_events')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_session_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_maintenance_tasks_status'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_due_date'), table_name='maintenance_tasks')
    op.drop_table('maintenance_tasks')
    op.drop_index(op.f('ix_leave_requests_status'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_employee_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_table('goods_receipt_notes')
    op.drop_table('couples')
    op.drop_index(op.f('ix_attendance_records_employee_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_attendance_date'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_asset_movements_asset_id'), table_name='asset_movements')
    op.drop_table('asset_movements')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_scheduled_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_stock_movements_item_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_readiness_checklists_department'), table_name='readiness_checklists')
    op.drop_index(op.f('ix_readiness_checklists_checklist_date'), table_name='readiness_checklists')
    op.drop_table('readiness_checklists')
    op.drop_index(op.f('ix_purchase_orders_status'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_patients_uhid'), table_name='patients')
    op.drop_index(op.f('ix_patients_phone'), table_name='patients')
    op.drop_index(op.f('ix_patients_full_name'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_tasks_status'), table_name='notification_tasks')
    op.drop_index(op.f('ix_notification_tasks_due_at'), table_name='notification_tasks')
    op.drop_index(op.f('ix_notification_tasks_assigned_to_id'), table_name='notification_tasks')
    op.drop_table('notification_tasks')
    op.drop_table('employees')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_code'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_users_employee_code'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_medicine_batches_medicine_id'), table_name='medicine_batches')
    op.drop_index(op.f('ix_medicine_batches_expiry_date'), table_name='medicine_batches')
    op.drop_table('medicine_batches')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('qa_task_templates')
    op.drop_table('procedure_charges')
    op.drop_index(op.f('ix_permissions_module'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('packages')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_dispatched_at'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_created_at'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_medicines_generic_name'), table_name='medicines')
    op.drop_table('medicines')
    op.drop_table('ledger_accounts')
    op.drop_table('lab_test_catalogue')
    op.drop_index(op.f('ix_inventory_items_name'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_category'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_table('idempotency_records')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
