"""widen blood_group column

Revision ID: e4a6fc4335ac
Revises: c9f299fef0e3
Create Date: 2026-08-27 06:37:58.555162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e4a6fc4335ac'
down_revision: Union[str, None] = 'c9f299fef0e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOTE: the autogenerated 'uq_role_permission' unique-constraint create
    # was dropped from this migration — that constraint already exists as
    # part of role_permissions' composite primary key from the initial
    # migration; autogenerate's constraint-naming comparison produced a
    # false positive. Only the actual intended change (widening
    # blood_group to fit "B Positive"/"O Positive") remains here.
    op.alter_column('patients', 'blood_group',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=16),
               existing_nullable=True)


def downgrade() -> None:
    op.alter_column('patients', 'blood_group',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
